version: "3.9"

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: microblog
      POSTGRES_PASSWORD: microblog
      POSTGRES_DB: microblog
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U microblog"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    depends_on:
      db:
        condition: service_healthy  # Ждём готовности БД
    environment:
      DATABASE_URL: postgresql://microblog:microblog@db:5432/microblog
    ports:
      - "8000:8000"
    volumes:
      - ./media:/app/media
    command: >
      sh -c "python create.py && uvicorn app.main:app --host 0.0.0.0 --port 8000"

volumes:
  pgdata: